### ISSUE TITLE
Unable to process files exported from Illustrator Assets 

### ISSUE THREAD

**Issue by prokash-sarkar** [jebo87/Illustrator-to-android#1]
After running the script, I'm getting the following error:

`TypeError: move() got an unexpected keyword argument 'copy_function'`

Operating System: Windows 10
Python Version: Python 3.4.3

**Comment by jebo87** [comment]
for this to work you need Python 3.5. You can also try removing that last parameter in the function, try replacing move(filename,dst,copy_function=copy2) to move(filename,dst)

Please refer to http://python.readthedocs.io/en/latest/whatsnew/3.5.html for more information

This is taken from the link above: The move() function now accepts a copy_function argument, allowing, for example, the copy() function to be used instead of the default copy2() if there is a need to ignore file metadata when moving. (Contributed by Claudiu Popa in bpo-19840.)
